alias u='sudo apt -qq update -y && sudo apt -qq upgrade -y && sudo apt -qq autoremove -y'
alias s='git status'
alias b='git branch'
alias l='git log'
alias a='git add -A'
alias c='git commit'
alias ca='git commit --amend'
alias r='rspec .'
alias rf='rspec ./spec/features/'
alias bu='bundle'
alias rse='bin/rails db:environment:set RAILS_ENV=development'
alias rs='bin/rails server --binding=0.0.0.0'
alias rc='bin/rails console'
alias dbc='bin/rails db:create'
alias dbm='bin/rails db:migrate'
alias dbt='bin/rails db:test:prepare'
alias dbd='bin/rails db:drop'
alias dbs='bin/rails db:seed'
alias db='rse && dbd && dbc && dbm && dbt && dbs'
alias dbr='bu && db && r'
alias dbrs='bu && db && rs'
alias e='exit'
alias off='sudo poweroff'
alias gph='git push heroku master'
alias ho='heroku open'
alias jr='cd ~/Documents/Journal\ of\ Repetitions\ All\ Files/akadan/'
alias da='cd ~/Documents/Device\ Advice\ All\ Files/device-advice'
alias v='vim'
